### ISSUE TITLE
No ZIPs

### ISSUE THREAD

**Issue by r-barnes** [bipinporwal/NCL_to_Python#1]
Github repos are not meant to source control zips and tar.gz files. Please unpack these files and track the individual files separately.

Please model your repo off of the [JOSS checklist](https://joss.readthedocs.io/en/latest/review_checklist.html) and [this repo](https://github.com/r-barnes/Barnes2020-FillSpillMerge) since they roughly cover what I'll be looking for.

Please also be sure your code is complete, compiles, and is well-commented.

**Comment by bipinporwal** [comment]
Dear Prof. Barnes, 
Thanks for point out this issue. I have updated the repository as suggested by you. Please check it and let me know if more details for the code is needed. 
Best, 
Bipin
