### ISSUE TITLE
More intuitive input format

### ISSUE THREAD

**Issue by r-barnes** [bipinporwal/NCL_to_Python#3]
Unless there's some strong reason for it, the input approach taken in, e.g. https://github.com/bipinporwal/NCL_to_Python/tree/master/Test_examples/month_to_season_serial seems difficult to work with.

Please replace all such interfaces with, e.g., Python's standard argparse library: https://docs.python.org/3/library/argparse.html

**Comment by bipinporwal** [comment]
Dear Richard, 
I have modified all the code as suggested. Now all support the argparse library. 
Thanks, 
 Bipin
